version: 1.0
jobs:
  deploy:
    steps:
      - node -v
      - pip install -r requirements.txt -t .
      - npm install -g zcatalyst-cli
      - catalyst deploy --token <YOUR_TOKEN>
stages:
  - name: deploy
    jobs:
      - deploy
